CREATE DATABASE sinialo;
USE sinialo;

CREATE TABLE users (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(150) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    country_ISO VARCHAR(50) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE countries(
	country_id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	country_ISO VARCHAR(50) NOT NULL ,
    country_name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE cities(
	city_id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    city_name VARCHAR(100) NOT NULL,
    country_id INT NOT NULL,
CONSTRAINT cityCountry FOREIGN KEY (country_id) REFERENCES `countries`(country_id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE airports(
	airport_id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    airportName VARCHAR(255) NOT NULL,
    city VARCHAR(150) NOT NULL,
    country_ID VARCHAR(100) NOT NULL,
    countryName VARCHAR(200) NOT NULL
    );
	
    
CREATE TABLE preferences(
	preference_id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(150) NOT NULL,
    city VARCHAR(150) NOT NULL,
    preference VARCHAR(250) NOT NULL);

CREATE TABLE requests(
	request_id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	requestfrom VARCHAR(140) NOT NULL,
    requestto VARCHAR(140) NOT NULL);
    
CREATE TABLE friends(
	friendship_id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    friend1 VARCHAR(140) NOT NULL,
    friend2 VARCHAR(140) NOT NULL);